name: Package exe with PyInstaller - Windows

# Controls when the workflow will run
on:
  # Triggers the workflow on push
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller --clean --onefile --icon assets/AutomatedSweeps.ico -y -n  "AutomatedSweeps" --add-data "assets;assets" --add-data "src/ui.tcss:." src/main.py
    - uses: actions/upload-artifact@v4
      with:
        path: dist/*